GROUP_REPOS = [
    {
        "name": "JOMS",
        "gitLinks": ["https://github.com/JOMS-inc/JOMSearch.git"],
        "backend": "http://20.91.229.193:8080/",
        "frontend": "http://20.91.229.193:8080/",
        "monitoring": "",
        "stack": ["go", "SQLite"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "visionJAMx",
        "gitLinks": ["https://github.com/visionJAMx/whoknows"],
        "backend": "http://4.165.140.243:8080/",
        "frontend": "http://4.165.140.243:8080/",
        "monitoring": "",
        "stack": ["Go", "Gin", "SQLite"],
        "documentation": [],
        "sla": "",
    }, 
    { 
        "name": "WeKnowXD",
        "gitLinks": ["https://github.com/WeKnowXD/WeKnowXD_Project"],
        "backend": "http://51.120.81.214:8080/",
        "frontend": "http://51.120.81.214:8080/",
        "monitoring": "",
        "stack": ["Go", "Go Standard Library", "SQLite3"],
        "documentation": ["https://github.com/WeKnowXD/WeKnowXD_Doc"],
        "sla": "",
    }, 

    {
        "name": "MaxiKnows",
        "gitLinks": ["https://github.com/maxiknows/maxi-knows.git"],
        "backend": "http://68.221.17.27:8080/",
        "frontend": "http://68.221.17.27:8080/",
        "monitoring": "",
        "stack": ["Go", "Go Standard Library", "SQLite"],
        "documentation": [],
        "sla": "",
    },
    
    {
    "name": "JakobMagnusBardie",
    "gitLinks": ["https://github.com/JacobMagnusBardie/WhoKnowsWho"],
    "backend": "http://20.100.207.69:8080/",
    "frontend": "http://20.100.207.69:8080/",
    "monitoring": "",
    "stack": [
        "Go", 
        "Go Standard Libary", 
        "SQLite3"
        ],
    "documentation": [
        "https://github.com/JacobMagnusBardie/WhoKnowsWho/blob/dev/backend/API-specs/swagger.json"
        ],
    "sla": "",
},
    {
        "name": "GenZM0nks",
        "gitLinks": ["https://github.com/GenZM0nks/AscendingMonk"],
        "backend": "http://20.251.205.81:8080/",
        "frontend": "http://20.251.205.81:8080/",
        "monitoring": "",
        "stack": ["Go", "Go Standard Library", "sqlite3" "swag", "revive"],
        "documentation": ["https://github.com/GenZM0nks/AscendingMonk/blob/main/docs/swagger.yaml"],
        "sla": "",
    },
    {
        "name": "Group Group",
        "gitLinks": ["https://github.com/Gruppegruppe/SearchEngine"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
    "name": "devops-gruppe-2",
    "gitLinks": ["https://github.com/devops-gruppe-2/search-engine"],
    "backend": "http://20.250.11.23:8080/api/",
    "frontend": "http://20.250.11.23:8080/",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
]
